name: bpi-r3 v1.2 images
on:
   workflow_dispatch:
   schedule:
    - cron: '01 08 * * *'
jobs:
    build:
        name: Build BPI-R3 v1.2 Images
        runs-on: ubuntu-latest
        steps:
            - name: Maximize build space
              uses: easimon/maximize-build-space@master
              with:
                root-reserve-mb: 512
                swap-size-mb: 1024
                remove-dotnet: 'true'
                overprovision-lvm: 'true'
                remove-android: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/mediatek/filogic/llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                tar -xvf llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                git apply 0001-bpi-r31.patch
                git apply kmod-apk.patch
                git apply 01-ip-addr.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/f327d1fcae5513be3abbeea1c6696c1da845a635/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/89452f476c58d91de06e84560e5762b8e5df456e/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                cd -
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mkdir -p files/www/repo
                mv r31 .config
                echo "# CONFIG_ARM64_CONTPTE is not set" >> target/linux/generic/config-6.12
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                tar -czvf bin/targets/mediatek/filogic/packages.tar.gz bin/targets/mediatek/filogic/packages
                rm -rf bin/targets/mediatek/filogic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: v1.2
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: BPI-R3 v1.2 Images ${{ env.D }}
                tag: v1.2
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/mediatek/filogic/*
