name: Build rockchip-pr
on:
   workflow_dispatch:
jobs:
    build:
        name: Build rockchip-pr
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.4'
            - name: checkout
              uses: actions/checkout@v4
            - name: Build pr
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cd openwrt
                wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/19388.patch
                git apply 19388.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                echo "# CONFIG_ARM64_CONTPTE is not set" >> target/linux/generic/config-6.12
                echo "# CONFIG_DRM_WERROR is not set" >> target/linux/generic/config-6.12
                echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/opt/hostedtoolcache/go/1.24.4/arm64/bin"' >> .config
                wget https://downloads.openwrt.org/snapshots/targets/rockchip/armv8/config.buildinfo -O .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/rockchip/armv8/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: rockchip-6.12-pr
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: Rockchip v6.12 Firmware Images ${{ env.D }}
                tag: rockchip-6.12-pr
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*

