name: Build rockchip arm64 v3
on:
   workflow_dispatch:
jobs:
    build:
        name: Build rockchip
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
            - name: checkout
              uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.5'
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/config-rockchip-v3 openwrt/
                cd openwrt
                git remote add source https://github.com/mj22226/source.git
                git fetch source
                git switch linux-6.6
                git format-patch main...linux-6.6 --stdout > 001.patch
                git checkout main
                git apply 001.patch
                wget https://raw.githubusercontent.com/anon540/r3/refs/heads/main/r3/0001-ar.patch
                wget https://github.com/anon1045/e27xx/commit/66332b9cebe3ef77cf4b4217877e059353bdcca3.patch
                git apply 0001-ar.patch
                git apply 66332b9cebe3ef77cf4b4217877e059353bdcca3.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/363cefecd314e45b49d8eafff8473fcf/raw/f327d1fcae5513be3abbeea1c6696c1da845a635/01-diskman.patch
                git apply 01-diskman.patch
                cd -
                cd  feeds/packages
                wget https://patch-diff.githubusercontent.com/raw/openwrt/packages/pull/25783.patch
                wget https://gist.githubusercontent.com/mj22226/351f11e66f08f06e37a985719a31ddb4/raw/b35ba7a3aac1949bd6bbeaad065a0a93dc3c34f0/01-cpu.patch
                wget https://gist.githubusercontent.com/mj22226/b66f5c1bd5fc7e1cb3cf2c690b5dbd5a/raw/b955e726cbb0948d932c8d6143229ad604320149/20-lxc.patch
                git apply 01-cpu.patch
                git apply 20-lxc.patch
                git apply 25783.patch
                cd -
                sed -i "71s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "84s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "195s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "212s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                wget https://github.com/mj22226/openwrt-arm64/releases/download/rockchip-18.1.7/llvm-bpf-18.1.7.Linux-aarch64.tar.zst
                tar -xvf llvm-bpf-18.1.7.Linux-aarch64.tar.zst
                mv config-rockchip-v3 .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/9a69bb754a83e8a5cf03fcc60d62d473/raw/cc6f36831d6098de4a7fccf04a312d36a0dbc999/01-key.patch
                git apply 01-key.patch
                make download -j32
                rm 01-key.patch
                make -j$(nproc) 'IGNORE_ERRORS=n m' || true
                tar -czvf bin/targets/rockchip/armv8/packages.tar.gz bin/targets/rockchip/armv8/packages || true
                tar -czvf bin/targets/rockchip/armv8/logs.tar.gz logs
                rm -rf bin/targets/rockchip/armv8/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: rockchip-arm64-6.6-v3
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: Rockchip Firmware Images v3 ${{ env.D }}
                tag: rockchip-arm64-6.6-v3
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*

