name: Debug Session V2
on:
   workflow_dispatch:
jobs:
    build:
        name: Debug Session V2
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y nano subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.4'
                cache: false
            - name: checkout
              uses: actions/checkout@v4
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3



