name: Debug Session V2
on:
   workflow_dispatch:
jobs:
    build:
        name: Debug Session V2
        runs-on: ubuntu-24.04-arm
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y subversion build-essential gettext 2to3 python3-pyelftools python3-distutils-extra hardinfo
                wget https://github.com/HorlogeSkynet/archey4/releases/download/v4.15.0.0/archey4_4.15.0.0-1_all.deb
                sudo apt install ./archey4_4.15.0.0-1_all.deb
            - name: checkout
              uses: actions/checkout@v4
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3

