name: wndr3800 images
on:
   workflow_dispatch:
jobs:
    build:
        name: Build wndr3800 Images
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cp -rf r3/* openwrt/
                cd openwrt
                wget https://downloads.openwrt.org/snapshots/targets/ath79/generic/llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                tar -xvf llvm-bpf-18.1.7.Linux-x86_64.tar.zst
                git apply 0001-bpi-r31.patch
                git apply 38.patch
                wget https://github.com/mj22226/openwrt/commit/848e171336e93686c886333ef978537b35c090d6.patch
                wget https://github.com/mj22226/openwrt/commit/cd3b961bd2bccd10f385fa94bd55285113f27da0.patch
                wget https://github.com/mj22226/openwrt/commit/8b9b1723955a93498ed6df58f3b22a92fb991aaa.patch
                wget https://github.com/mj22226/openwrt/commit/0964b12f6d827e73a0f96ef118d81f4d4263bc46.patch
                git apply 848e171336e93686c886333ef978537b35c090d6.patch
                git apply cd3b961bd2bccd10f385fa94bd55285113f27da0.patch
                git apply 8b9b1723955a93498ed6df58f3b22a92fb991aaa.patch
                git apply 0964b12f6d827e73a0f96ef118d81f4d4263bc46.patch
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://github.com/openwrt/luci/commit/10319bbcc4fa50e29e18ecc0b29c8a26124604f2.patch
                git apply 10319bbcc4fa50e29e18ecc0b29c8a26124604f2.patch
                cd -
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                echo "CONFIG_PACKAGE_luci-app-filemanager=y" >> .config
                mv w3800 .config
                make defconfig
                make download -j32
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/ath79/generic/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Delete tag
              uses: ClementTsang/delete-tag-and-release@v0.4.0
              with:
                delete_release: true
                tag_name: w3800
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Create release
              uses: ncipollo/release-action@v1.14.0
              with:
                allowUpdates: true
                name: WRND3800 Images ${{ env.D }}
                tag: w3800
                replacesArtifacts: true
                makeLatest: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/ath79/generic/*
